sudo: false

language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

python:
  - "2.7"
  - "3.2"

# command to install dependencies
addons:
  apt:
    packages:
    - libpcre3-dev
    - python-smbus
    - python-dev

before_install:
  - pip install --user codecov
install: "pip install -r requirements.txt"

after_success:
  - codecov --file coverage/lcov.info --disable search
# command to run tests
script: nosetests

notifications:
  email: false
